security:
    enable_authenticator_manager: true
    providers:
        klanlar_provider:
            entity:
                class: App\Entity\Player
                property: token
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: false
            lazy: true
            provider: klanlar_provider
            custom_authenticators:
                - App\Security\Authenticator
            #remember_me:
             #   secret: '%kernel.secret%'
              #  lifetime: 3600
               # path: ^/api
    access_control:
        - { path: ^/api/public, roles: PUBLIC_ACCESS }
        - { path: ^/api, roles: ROLE_USER }