security:
    enable_authenticator_manager: true
    providers:
        users_in_memory: { memory: null }
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: true
        main:
            anonymous: false
            lazy: true
            provider: users_in_memory
            custom_authenticators:
                - App\Security\Authenticator
    access_control:
        - { path: ^/auth, roles: PUBLIC_ACCESS }
        - { path: ^/api, roles: ROLE_USER }