security:
    enable_authenticator_manager: true
    providers:
        klanlar_provider:
            entity:
                class: App\Entity\Player
                property: apiToken
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: false
            lazy: true
            provider: klanlar_provider
            custom_authenticators:
                - App\Security\Authenticator
            logout:
                path: logout
    access_control:
        - { path: ^/public, roles: PUBLIC_ACCESS }
        - { path: ^/api, roles: ROLE_USER }