version: "3"
services:
  php:
    image: klanlar:php-7.4
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: klanlar-php
    volumes:
      - .:/var/www
    networks:
      - klanlar_dev

    #blackfire:
    #image: blackfire/blackfire
      #environment:
      #BLACKFIRE_SERVER_ID: '%env(BLACKFIRE_SERVER_ID)%'
      #BLACKFIRE_SERVER_TOKEN: '%env(BLACKFIRE_SERVER_TOKEN)%'
      #BLACKFIRE_CLIENT_ID: '%env(BLACKFIRE_CLIENT_ID)%'
      #BLACKFIRE_CLIENT_TOKEN: '%env(BLACKFIRE_CLIENT_TOKEN)%'
    #ports: ["8707"]
    #container_name: klanlar-blackfire
      #volumes:
      #- .:/var/www
      #networks:
      #- klanlar_dev

  nginx:
    image: klanlar:nginx-1.17
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    container_name: klanlar-nginx
    ports:
      - 81:80
      - 443:443
    volumes:
      - .:/var/www
    networks:
      - klanlar_dev

  mysql:
    image: mysql:8.0
    container_name: klanlar-mysql
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: '%env(MYSQL_ROOT_PASSWORD)%'
      MYSQL_DATABASE: '%env(MYSQL_DATABASE)%'
      MYSQL_USER: '%env(MYSQL_USER)%'
      MYSQL_PASSWORD: '%env(MYSQL_PASSWORD)%'
    networks:
      - klanlar_dev

networks:
  klanlar_dev:
    driver: bridge