version: "3"
services:
  php:
    image: klanlar:php-7.4
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: klanlar_php
    volumes:
      - .:/var/www
    networks:
      - klanlar_dev

    #blackfire:
    #image: blackfire/blackfire
      #environment:
      #BLACKFIRE_SERVER_ID: '%env(BLACKFIRE_SERVER_ID)%'
      #BLACKFIRE_SERVER_TOKEN: '%env(BLACKFIRE_SERVER_TOKEN)%'
      #BLACKFIRE_CLIENT_ID: '%env(BLACKFIRE_CLIENT_ID)%'
      #BLACKFIRE_CLIENT_TOKEN: '%env(BLACKFIRE_CLIENT_TOKEN)%'
    #ports: ["8707"]
    #container_name: klanlar-blackfire
      #volumes:
      #- .:/var/www
      #networks:
      #- klanlar_dev

  nginx:
    image: klanlar:nginx-1.17
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    container_name: klanlar_nginx
    ports:
      - 81:80
      - 443:443
    volumes:
      - .:/var/www
    networks:
      - klanlar_dev

  mysql:
    image: mysql:8.0
    container_name: klanlar_mysql
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql:/var/lib/mysql
    command: ["--default-authentication-plugin=mysql_native_password"]
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: klanlar
      MYSQL_USER: morwoss
      MYSQL_PASSWORD: root
    networks:
      - klanlar_dev

  mongo:
    image: mongo:latest
    build:
      context: .
      dockerfile: docker/mongodb/Dockerfile
    container_name: klanlar_mongo
    restart: always
    ports:
      - 27018:27017
    volumes:
      - ./docker/mongodb/mongod.conf:/etc/mongod.conf
      - ./docker/mongodb/initdb.d/:/docker-entrypoint-initdb.d/
      - ./docker/mongodb/data/db/:/data/db/
      - ./docker/mongodb/data/log/:/var/log/mongodb/
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: klanlar
    command: mongod --port 27018
    expose:
      - 27018
    networks:
      - klanlar_dev

  redis:
    image: redis:latest
    build:
      context: .
      dockerfile: docker/redis/Dockerfile
    container_name: klanlar_redis
    restart: always
    ports:
    - 6380:6379
    volumes:
      - ./docker/redis/data:/var/lib/redis
      - ./docker/redis/redis.conf:/var/lib/redis/redis.conf
    command: redis-server --port 6380
    networks:
      - klanlar_dev

networks:
  klanlar_dev:
    driver: bridge