public:
  resource: "resources/public.yaml"
  prefix: /api/public

player:
  resource: "resources/player.yaml"
  prefix: /api/player

village:
  resource: "resources/village.yaml"
  prefix: /api/village