public:
  resource: "resources/public.yaml"
  prefix: /public

player:
  resource: "resources/player.yaml"
  prefix: /api/player

village:
  resource: "resources/village.yaml"
  prefix: /api/village

building:
  resource: "resources/building.yaml"
  prefix: /api/building

command:
  resource: "resources/command.yaml"
  prefix: /api/command