unit_command:
  methods: POST
  path: /unit
  controller: App\Controller\CommandController::unitCommandAction

building_command:
  methods: POST
  path: /building
  controller: App\Controller\CommandController::buildingCommandAction

cancel_unit_command:
  methods: DELETE
  path: /unit
  controller: App\Controller\CommandController::cancelUnitCommandAction

cancel_building_command:
  methods: DELETE
  path: /building
  controller: App\Controller\CommandController::cancelBuildingCommandAction