logout:
  methods: POST
  path: /logout

player_world:
  methods: GET
  path: /world
  controller: App\Controller\PlayerController::playerWorld

play:
  methods: GET
  path: /play
  controller: App\Controller\PlayerController::play

world_login:
  methods: GET
  path: /login
  controller: App\Controller\LoginController::worldLogin