public_login:
  methods: POST
  path: /login
  controller: App\Controller\LoginController::login

public_register:
  methods: POST
  path: /register
  controller: App\Controller\RegisterController::register